### ISSUE TITLE
Feat: Setup emotion

### ISSUE THREAD

**Issue by Fansoa** [ChristopherDebray/projet_git_3iwj_new#21]
# Conception steps achieved

- [x] The right labels have been added
- [x] Collaborator working on the feature as been defined
- [x] The specifications have been written
- [x] The technical strategy has been written

# Summary

Setup de la library emotion afin de styliser les composants react

# Specifications 

Dernière version d'emotion

**Comment by ChristopherDebray** [comment]
Peux tu spécifier dans le ticket la version d'emotion ?

**Comment by Fansoa** [comment]
Voici les deux librairies nécessaire au fonctionnement d'emotion:
    "@emotion/react": "^11.11.0",
    "@emotion/styled": "^11.11.0"
